server:
  port: 8080
  contextPath: /ControleDespesasApp
---
spring:
  profiles: local,default
datasource:
  sampleapp:
    url: jdbc:mysql://127.0.0.1:3306/db_cdesp
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect